Repository RioChndr/jaksel-language, pull requests merged in 2022-04, with the labels that each got.

#14 feature: add procedure syntax and example
  README.md
  example/example-function.jaksel
  jaksel-interpreter.js
Labels: enhancement

#31 Fix async and string function
  README.md
  example/example-async.jaksel
  lib/logics/index.js
  lib/logics/parser/awaitProcess.js
  lib/logics/parser/functionCall.js
  lib/logics/parser/functionDeclarationAsyncBegin.js
Labels: bug

#35 WIP: Unit test setup
  __test__/example/e2e-test.js
  __test__/example/example1.test.js
  __test__/logics/parser/conditionIf.test.js
  __test__/logics/parser/consoleLog.test.js
  __test__/logics/parser/constAssign.test.js
  __test__/logics/parser/varAssign.test.js
  __test__/logics/parser/varReassign.test.js
  __test__/logics/test-parser-helper.js
  lib/utils/execCmd.js
  lib/utils/index.js
  package.json
Labels: enhancement, help wanted
